name: Log GitHub Clone Traffic Daily

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at 00:00 UTC
  workflow_dispatch: # Manual trigger

permissions:
  contents: write # required for git push to work
jobs:
  log-traffic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch clone traffic from GitHub API
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB_TRAFFIC }}
          REPO: ${{ github.repository }}
        run: |
          DATE=$(date +%F)
          mkdir -p traffic_logs/$DATE

          # Clone data
          curl -H "Authorization: token $GH_TOKEN" \
            https://api.github.com/repos/$REPO/traffic/clones \
            -o traffic_logs/$DATE/clones.json
            

          # Visitor data
          curl -H "Authorization: token $GH_TOKEN" \
            https://api.github.com/repos/$REPO/traffic/views \
            -o traffic_logs/$DATE/visitors.json
            
      - name: List logged files
        run: ls -l traffic_logs/$DATE
            
      - name: Commit and push logs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add traffic_logs/
          git commit -m "Add traffic data for $(date +%F)" || echo "No changes to commit"
          git push
